polar:
  greeting: "Welcome to the catalog from the config server"
user:
  language: en 
  country: US
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
	hikari: 
      connection-timeout: 2000 
      maximum-pool-size: 5